apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  clusterIP: {{ .Values.postgres.clusterIP }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "db-service"
  replicas: {{ .Values.postgres.replicas }}
  template:
    metadata:
      labels:
        app: postgres
    spec:
      {{- if .Values.postgres.securityContext }}
      securityContext:
        {{- toYaml .Values.postgres.securityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
              name: postgres
          volumeMounts:
            - name: postgres-data
              mountPath: {{ .Values.postgres.dataPath }}
          env:
            - name: {{ .Values.postgres.envUser }}
              valueFrom:
                secretKeyRef:
                  name: diario-obra-secret
                  key: DB_USER
            - name: {{ .Values.postgres.envPassword }}
              valueFrom:
                secretKeyRef:
                  name: diario-obra-secret
                  key: DB_PASSWORD
            - name: {{ .Values.postgres.envDatabase }}
              valueFrom:
                configMapKeyRef:
                  name: diario-obra-config
                  key: DB_NAME
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storage }}
