apiVersion: v1
kind: Secret
metadata:
  name: diario-obra-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_USER: {{ .Values.database.user | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  MINIO_USER: {{ .Values.storage.user | quote }}
  MINIO_PASSWORD: {{ .Values.storage.password | quote }}
