apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: deploy
  namespace: tekton-pipelines
spec:
  params:
    - name: database-user
    - name: database-password
    - name: storage-user
    - name: storage-password
  workspaces:
    - name: shared-workspace
  tasks:
    - name: build
      workspaces:
        - name: source
          workspace: shared-workspace
      taskRef:
        name: build-image
    - name: deploy
      params:
        - name: database-user
          value: $(params.database-user)
        - name: database-password
          value: $(params.database-password)
        - name: storage-user
          value: $(params.storage-user)
        - name: storage-password
          value: $(params.storage-password)
      workspaces:
        - name: source
          workspace: shared-workspace
      taskRef:
        name: deploy
      runAfter:
        - build
