apiVersion: v1
kind: ConfigMap
metadata:
  name: diario-obra-config
  namespace: diario-obra
data:
  DB_HOST: "db-service"
  DB_PORT: "5432"
  DB_NAME: "diario_obra"
  MINIO_ENDPOINT: "minio-service:9000"
