apiVersion: v1
kind: Secret
metadata:
  name: diario-obra-secret
  namespace: diario-obra
type: Opaque
stringData:
  DB_USER: "CHANGE_ME"
  DB_PASSWORD: "CHANGE_ME"
  MINIO_USER: "CHANGE_ME"
  MINIO_PASSWORD: "CHANGE_ME"
