apiVersion: v1
kind: Secret
metadata:
  name: diario-obra-secret
  namespace: diario-obra
type: Opaque
stringData:
  DB_USER: "v1c_g4b"
  DB_PASSWORD: "v1c_g4b_auth00"
  MINIO_USER: "v1c_g4b_minio"
  MINIO_PASSWORD: "v1c_gab_minio_auth00"
